### ISSUE TITLE
Enrollment class

### ISSUE THREAD

**Issue by TheObtuseAutodidact** [brantwellman/headcount#6]
An Enrollment instance holds the enrollment data for a single district

init like so: 
e = Enrollment.new({:name => "ACADEMY 20", :kindergarten_participation => {2010 => 0.3915, 2011 => 0.35356, 2012 => 0.2677})

def kindergarten_participation_by_year
returns a hash of key: years and values: percentage 

def kindergarten_participation_in_year(year)
returns percentage (fixnum)

**Comment by brantwellman** [comment]
Class is created and tested
